# Generated by Django 2.1.5 on 2020-05-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(related_name='get_posts', to='services.Category', verbose_name='Categoría'),
        ),
    ]
